drop table if exists t;
create table t (
  id int primary key generated by default as identity,
  color text not null,
  validity tstzrange not null
);

insert into t(color, validity) values ('green', '[2020-01-01,2020-03-01)'), ('blue', '[2020-03-01,)');
