CREATE TABLE IF NOT EXISTS public.vectors
(
    _id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    vector double precision[] NOT NULL,
    CONSTRAINT "Vector_pkey" PRIMARY KEY (_id)
);
